"""empty message

Revision ID: 861a7ffe6503
Revises: 39c8bcfd48ad
Create Date: 2019-12-20 05:28:19.203507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861a7ffe6503'
down_revision = '39c8bcfd48ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('course_lecturers',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('lecturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], )
    )
    op.create_table('course_students',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_students')
    op.drop_table('course_lecturers')
    op.drop_table('course')
    # ### end Alembic commands ###
