"""empty message

Revision ID: c7328eac6ab7
Revises: 861a7ffe6503
Create Date: 2019-12-20 09:22:12.879288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7328eac6ab7'
down_revision = '861a7ffe6503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_lecturers', type_='foreignkey')
    op.drop_constraint(None, 'course_lecturers', type_='foreignkey')
    op.create_foreign_key(None, 'course_lecturers', 'course', ['course_id'], ['public_id'])
    op.create_foreign_key(None, 'course_lecturers', 'lecturer', ['lecturer_id'], ['public_id'])
    op.drop_constraint(None, 'course_students', type_='foreignkey')
    op.drop_constraint(None, 'course_students', type_='foreignkey')
    op.create_foreign_key(None, 'course_students', 'course', ['course_id'], ['public_id'])
    op.create_foreign_key(None, 'course_students', 'student', ['student_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_students', type_='foreignkey')
    op.drop_constraint(None, 'course_students', type_='foreignkey')
    op.create_foreign_key(None, 'course_students', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_students', 'student', ['student_id'], ['id'])
    op.drop_constraint(None, 'course_lecturers', type_='foreignkey')
    op.drop_constraint(None, 'course_lecturers', type_='foreignkey')
    op.create_foreign_key(None, 'course_lecturers', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_lecturers', 'lecturer', ['lecturer_id'], ['id'])
    # ### end Alembic commands ###
